#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — issue #3: provision the Sanity project and deploy credentials.
# ──────────────────────────────────────────────────────────────────────────

# record_doc PATTERN REPLACEMENT — upsert a line in docs/infrastructure.md
# whose start matches PATTERN, replacing the whole line with REPLACEMENT.
# Idempotent: safe to re-run since REPLACEMENT still starts with PATTERN.
INFRA_DOC="docs/infrastructure.md"
record_doc() {
  local pattern="$1" replacement="$2"
  [[ -f "$INFRA_DOC" ]] || return 0
  if grep -qF "$pattern" "$INFRA_DOC"; then
    local tmp; tmp=$(mktemp)
    awk -v pat="$pattern" -v rep="$replacement" \
      '{ if (index($0, pat) == 1) print rep; else print $0 }' "$INFRA_DOC" > "$tmp"
    mv "$tmp" "$INFRA_DOC"
    printf '  %s✓ updated%s %s\n' "$GREEN" "$RESET" "$INFRA_DOC"
  fi
}

TOTAL_STAGES=8

banner "ACM Hotels — deploy credentials + go live (issues #3, #5)"

# ── Stage 1: Sanity project ────────────────────────────────────────────────
stage "Sanity — project and dataset"
say "Create (or point at an existing) Sanity project for ACM Hotels' content."
open_url "https://www.sanity.io/manage"
step "Create project → name it \"ACM Hotels\" (or pick the existing one)."
step "Keep the default dataset name \"production\" unless you have a reason not to."
step "On the project page (Manage → project → Settings → API), copy the Project ID."
ask SANITY_PROJECT_ID "Project ID:"
ask SANITY_DATASET "Dataset [production]:"
SANITY_DATASET="${SANITY_DATASET:-production}"
write_env NEXT_PUBLIC_SANITY_PROJECT_ID "$SANITY_PROJECT_ID"
write_env NEXT_PUBLIC_SANITY_DATASET "$SANITY_DATASET"
set_var SANITY_PROJECT_ID "$SANITY_PROJECT_ID"
set_var SANITY_DATASET "$SANITY_DATASET"
record_doc "- Project ID:" "- Project ID: $SANITY_PROJECT_ID"
record_doc "- Dataset:" "- Dataset: $SANITY_DATASET"

# ── Stage 2: dedicated SSH deploy key ──────────────────────────────────────
stage "SSH key — dedicated ACM Hotels deploy pair"
SSH_KEY_PATH="$HOME/.ssh/acm_hotels_deploy"
say "Generating a fresh ed25519 key pair, separate from tic-tac-toe-online's deploy key."
if [[ -f "$SSH_KEY_PATH" ]]; then
  note "Already exists: $SSH_KEY_PATH"
  if confirm "Regenerate it?"; then
    rm -f "$SSH_KEY_PATH" "${SSH_KEY_PATH}.pub"
    ssh-keygen -t ed25519 -N "" -C "acm-hotels-deploy" -f "$SSH_KEY_PATH" >/dev/null
    say "Key regenerated."
  else
    say "Using the existing key."
  fi
else
  ssh-keygen -t ed25519 -N "" -C "acm-hotels-deploy" -f "$SSH_KEY_PATH" >/dev/null
  say "Key created: $SSH_KEY_PATH"
fi
chmod 600 "$SSH_KEY_PATH"
FINGERPRINT=$(ssh-keygen -lf "${SSH_KEY_PATH}.pub" | awk '{print $2}')
if confirm "Store this key's private half as the DEPLOY_SSH_KEY GitHub Actions secret?"; then
  set_secret DEPLOY_SSH_KEY "$(cat "$SSH_KEY_PATH")"
  record_doc "- SSH deploy key:" "- SSH deploy key: dedicated \`acm_hotels_deploy\` ed25519 pair (fingerprint $FINGERPRINT), not shared with tic-tac-toe-online. Private half stored as the \`DEPLOY_SSH_KEY\` GitHub Actions secret."
else
  SKIPPED+=("GitHub secret DEPLOY_SSH_KEY (set it manually: gh secret set DEPLOY_SSH_KEY < ${SSH_KEY_PATH})")
  warn "skipped — set it later with: gh secret set DEPLOY_SSH_KEY < ${SSH_KEY_PATH}"
fi
note "Public half (${SSH_KEY_PATH}.pub) is needed on the server in the next stage."

# ── Stage 3: authorize the public key on the Beget server ─────────────────
stage "Authorize the key on the server (Beget)"
say "Public key to add for the deploy user's ~/.ssh/authorized_keys:"
printf '\n%s\n\n' "$(cat "${SSH_KEY_PATH}.pub")"
ask SSH_HOST "Beget server host/IP:"
ask SSH_USER "Deploy user on the server:"
step "SSH in with your own existing access, e.g.: ssh ${SSH_USER}@${SSH_HOST}"
step "Append the key above to ~/.ssh/authorized_keys for ${SSH_USER} (or run: ssh-copy-id -i ${SSH_KEY_PATH}.pub ${SSH_USER}@${SSH_HOST})"
step "Do not reuse tic-tac-toe-online's key — this pair is ACM Hotels-only."
pause "Added the key on the server?"
say "Testing the connection with the new key..."
if ssh -i "$SSH_KEY_PATH" -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=6 \
     "${SSH_USER}@${SSH_HOST}" 'echo ok' >/dev/null 2>&1; then
  say "Connected successfully with the new key."
else
  warn "Could not connect with this key — check host/user and that the public key was actually added."
fi
write_env SSH_HOST "$SSH_HOST"
write_env SSH_USER "$SSH_USER"
set_var SSH_HOST "$SSH_HOST"
set_var SSH_USER "$SSH_USER"
record_doc "- Host:" "- Host: $SSH_HOST"
record_doc "- Deploy user:" "- Deploy user: $SSH_USER"

# ── Stage 4: confirm GHCR push access ──────────────────────────────────────
stage "GHCR — container registry push access"
say "Issue #5's pipeline will push images to GHCR. Checking whether the built-in GITHUB_TOKEN is enough."
REPO_SLUG=$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo "")
DEFAULT_PERMS="unknown"
if [[ -n "$REPO_SLUG" ]] && command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  DEFAULT_PERMS=$(gh api "repos/${REPO_SLUG}/actions/permissions/workflow" --jq '.default_workflow_permissions' 2>/dev/null || echo "unknown")
  note "repos/${REPO_SLUG} → default_workflow_permissions = ${DEFAULT_PERMS}"
else
  warn "gh not ready — couldn't check the repo's default workflow permissions."
fi
say "A workflow that declares 'permissions: packages: write' can normally push to GHCR with GITHUB_TOKEN — no separate PAT needed. Issue #5's workflow will declare that when it's added."
GHCR_NOTE="- Push access: default_workflow_permissions=${DEFAULT_PERMS}; GITHUB_TOKEN with explicit 'permissions: packages: write' in the workflow is expected to be sufficient (re-confirm once issue #5's workflow runs)."
if confirm "Create a separate PAT with write:packages anyway, as a fallback, and store it as a secret?"; then
  open_url "https://github.com/settings/tokens?type=beta"
  step "Fine-grained token → this repository → Permissions → Contents: Read, Packages: Read and write."
  step "Or a classic token at https://github.com/settings/tokens/new with scopes write:packages, read:packages."
  ask_secret GHCR_TOKEN "Paste the token:"
  set_secret GHCR_TOKEN "$GHCR_TOKEN"
  GHCR_NOTE="- Push access: default_workflow_permissions=${DEFAULT_PERMS}; a dedicated PAT is stored as the \`GHCR_TOKEN\` GitHub Actions secret."
else
  say "Skipping — relying on the built-in GITHUB_TOKEN."
fi
record_doc "- Push access:" "$GHCR_NOTE"

# ── Stage 5: DNS — subdomain for the ACM Hotels deploy ─────────────────────
stage "DNS — A-запись для partners.acm-hotels.ru"
say "Домен привязывается к серверу через shared edge-proxy (Fuberg/edge-proxy) — тот уже содержит site-блок для partners.acm-hotels.ru."
open_url "https://cp.beget.com"
step "Домены → acm-hotels.ru → раздел управления DNS-записями (название пункта меню зависит от текущего интерфейса Beget — ищите «DNS» или «Управление зоной», я не проверял этот экран вживую)."
step "Добавьте A-запись: имя \"partners\" → значение ${SSH_HOST} (тот же IP, что и для SSH выше)."
ask DOMAIN "Домен, который вы прописали [partners.acm-hotels.ru]:"
DOMAIN="${DOMAIN:-partners.acm-hotels.ru}"
pause "DNS-запись создана?"
note "Распространение DNS может занять от нескольких минут до нескольких часов."
write_env DOMAIN "$DOMAIN"
set_var DOMAIN "$DOMAIN"
record_doc "- Domain:" "- Domain: \`$DOMAIN\` — DNS A record → $SSH_HOST"

# ── Stage 6: redeploy the shared edge-proxy ─────────────────────────────────
stage "Редеплой shared edge-proxy (подхватить новый site-блок)"
say "Caddyfile в Fuberg/edge-proxy уже содержит блок для ${DOMAIN} — его нужно применить на сервере, чтобы Caddy начал проксировать и выпустил TLS-сертификат."
if confirm "Попробовать сделать это сейчас по SSH тем же ключом ACM Hotels (сработает, только если ${SSH_USER} также имеет доступ к /opt/edge-proxy)?"; then
  if ssh -i "$SSH_KEY_PATH" -o BatchMode=yes -o ConnectTimeout=6 "${SSH_USER}@${SSH_HOST}" \
       'cd /opt/edge-proxy && git pull && sudo docker compose up -d' >/dev/null 2>&1; then
    say "${GREEN}✓ edge-proxy передеплоен${RESET}"
  else
    warn "не получилось автоматически (нет доступа к /opt/edge-proxy этим пользователем, или каталог называется иначе) — сделайте вручную:"
    note "  ssh <тот-у-кого-есть-доступ>@${SSH_HOST} 'cd /opt/edge-proxy && git pull && sudo docker compose up -d'"
    SKIPPED+=("Редеплой edge-proxy на сервере (cd /opt/edge-proxy && git pull && sudo docker compose up -d)")
  fi
else
  SKIPPED+=("Редеплой edge-proxy на сервере (cd /opt/edge-proxy && git pull && sudo docker compose up -d)")
fi

# ── Stage 7: GHCR package visibility + trigger the Deploy workflow ─────────
stage "GHCR — публичный пакет и запуск деплоя"
PKG_NAME=$(printf '%s' "${REPO_SLUG#*/}" | tr '[:upper:]' '[:lower:]')
say "docker compose pull на сервере не логинится в registry — пакет должен быть публичным, иначе pull упадёт с ошибкой авторизации."
open_url "https://github.com/${REPO_SLUG}/pkgs/container/${PKG_NAME}"
step "Package settings (внизу справа) → Danger Zone → Change visibility → Public."
note "Если пакета ещё нет в списке — сначала должен отработать job build-and-push (он уже отрабатывал при прошлых push в main)."
confirm "Пакет сделан публичным?" || warn "без этого 'docker compose pull' на сервере не сработает — вернитесь к этому шагу позже"

say "Запускаю workflow Deploy заново, уже с секретами..."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1 && gh workflow run deploy.yml >/dev/null 2>&1; then
  say "${GREEN}✓ workflow запущен${RESET}"
else
  warn "не удалось запустить автоматически — запустите вручную: Actions → Deploy → Run workflow"
fi
open_url "https://github.com/${REPO_SLUG}/actions"
confirm "Workflow 'Deploy' завершился успешно (build-and-push, deploy, verify — все зелёные)?" || warn "проверьте логи упавшего job'а; типичные причины — DNS ещё не применился или пакет ещё не публичный"

# ── Stage 8: verify the live site ───────────────────────────────────────────
stage "Проверка живого сайта"
say "Проверяю https://${DOMAIN}..."
if curl -fsS "https://${DOMAIN}/" 2>/dev/null | grep -q 'data-health-check="ok"'; then
  say "${GREEN}✓ сайт отвечает и отдаёт health-check маркер${RESET}"
else
  warn "не смог получить маркер с https://${DOMAIN} — если DNS ещё не распространился или сертификат не выпустился, попробуйте позже: curl -sS https://${DOMAIN}/"
fi
open_url "https://${DOMAIN}"

finish
